name: Run Script Twice Daily

on:
  schedule:
    - cron: '0 1 * * 1-5' # 北京时间 15:30
    - cron: '30 7 * * 1-5'→ Runs at 07:30, Monday through Friday # 北京时间 15:30
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-job:
    runs-on: ubuntu-latest

    env:
      NAME: ${{ secrets.NAME }}   # ⭐统一放这里

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install pandas numpy requests matplotlib openpyxl

      - name: Make script executable
        run: chmod +x run.sh

      - name: Run script + send message
        run: |
          ./run.sh

          message=$(sed -n '81,83p' log.txt)
          echo "message: $message"
          # 去换行（拼成一行）
          message=$(echo "$message" | paste -sd " " -)
          
          # URL 编码（关键！）
          message=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$message'''))")

          url="https://api.chuckfang.com/${NAME}/${message}"
          echo "request url: $url"

          curl "$url"

      - name: Commit logs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add log.txt fund_data 
          git commit -m "update log" || echo "no changes"
          git push
